### ISSUE TITLE
[QUESTION] how is the grad bucket size ensured to be a multiple of dp world size?

### ISSUE THREAD

**Issue by jiayulu** [NVIDIA/Megatron-LM#561] opened 2023-10-26 05:40 UTC
@deepakn94  could you please point to the code that ensures the bucket size is divisible by the dp world size? from what i can see, a new bucket is created whenever the cumulative number of elements is bigger than or equal to the specified bucket size.

```
def shard_buffer(buffer):
    """
    Shard buffer into dp_size chunks of equal size.
    """
    data_parallel_world_size = parallel_state.get_data_parallel_world_size()
    assert buffer.numel() % data_parallel_world_size == 0     <-------------- how is this ensured?
    shard_size = buffer.numel() // data_parallel_world_size
    sharded_buffer = [
        buffer[(r * shard_size) : ((r + 1) * shard_size)] for r in range(data_parallel_world_size)
    ]
    return sharded_buffer
```

https://github.com/NVIDIA/Megatron-LM/blob/feac76a79148622d8f2a45d46c08a972a24784a3/megatron/core/distributed.py#L18-L28

**Comment by deepakn94** [comment] 2023-10-26 05:41
There is no such code right now; we are depending on "good numbers" for this to hold (e.g., if dp_size is a power of 2, this usually will not be an issue). But the assertion is needed for correctness. I am working on a patch to fix this.

**Comment by jiayulu** [comment] 2023-10-26 07:01
@deepakn94 thanks for the quick reply. another question: before your recent change, the ` build_model_gbuf_range` function uses `grad_buffer.numel` to calculate each dp rank's range:
```
    def build_model_gbuf_range(cls, model, dtype):
        data_parallel_rank = mpu.get_data_parallel_rank()
        data_parallel_world_size = mpu.get_data_parallel_world_size()

        # Grad buffer range.
        grad_buffer = model.grad_buffers[dtype]
        gbuf_size = grad_buffer.numel       <------------------------------------ here
        max_gbuf_range_size = int(math.ceil(gbuf_size / data_parallel_world_size))

        # All world ranges. (i.e., across all data parallel ranks)
        gbuf_world_all_ranges = []
        for r in range(data_parallel_world_size):
            gbuf_world_start = r * max_gbuf_range_size
            gbuf_world_end = min(gbuf_size, gbuf_world_start+max_gbuf_range_size)
            gbuf_world_range = Range(gbuf_world_start, gbuf_world_end)
            gbuf_world_all_ranges.append(gbuf_world_range)

        # Local DP's ranges.
        gbuf_world_range = gbuf_world_all_ranges[data_parallel_rank]
        gbuf_local_range = gbuf_world_range.normalize()
```
yet the `reduce_scatter` uses `grad_buffer.numel_padded` to split the grad buffer to dp ranks:
```
    def _get_local_view(self, buf):
        assert buf.numel() % self.data_parallel_size == 0
        shard_size = buf.numel() // self.data_parallel_size    <------------- here
        return buf[
            (self.data_parallel_rank * shard_size) : ((self.data_parallel_rank + 1) * shard_size)
        ]

    def all_reduce(self):
        assert (
            self.allreduce_handle is None and not self.allreduce_issued
        ), 'Should not have multiple all-reduces in flight at once'

        self.data /= self.data_parallel_size
        # Use async_op only when overlap_grad_reduce is True.
        if self.reduce_scatter:
            local_data_view = self._get_local_view(self.data)
            self.allreduce_handle = torch.distributed._reduce_scatter_base(
                local_data_view,
                self.data,
                group=self.data_parallel_group,
                async_op=self.overlap_grad_reduce,
            )
        else:
            self.allreduce_handle = torch.distributed.all_reduce(
                self.data, group=self.data_parallel_group, async_op=self.overlap_grad_reduce
            )
        self.allreduce_issued = True
```
this would cause the optimize to use the wrong gradients to update the params it owns, is that right?


https://github.com/NVIDIA/Megatron-LM/blob/0203a13faddd1a91f8d9f53fd858d73e9d3b973e/megatron/optimizer/distrib_optimizer.py#L123-L168

https://github.com/NVIDIA/Megatron-LM/blob/0203a13faddd1a91f8d9f53fd858d73e9d3b973e/megatron/model/distributed.py#L78-L104

**Comment by deepakn94** [comment] 2023-10-26 07:04
`buf` here is each bucket's buffer actually. We ran extensive tests to check for correctness, so I think the implementation is correct (when the assertion you pointed out doesn't fail).

**Comment by jiayulu** [comment] 2023-10-26 07:11
@deepakn94 it was the same before bucketing was added, so that too relies on `grad_buffer.numel_padded` being equal to `grad_buffer.numel`?

`get_model_buffer_dp_views` uses `grad_buffer.numel_padded`
https://github.com/NVIDIA/Megatron-LM/blob/115b6776813eb182237da6c8b9c78c6ae05d8ab1/megatron/optimizer/distrib_optimizer.py#L791

`build_model_gbuf_range` uses `grad_buffer.numel`
https://github.com/NVIDIA/Megatron-LM/blob/115b6776813eb182237da6c8b9c78c6ae05d8ab1/megatron/optimizer/distrib_optimizer.py#L140

**Comment by jiayulu** [comment] 2023-10-26 22:53
@shoeybi could you please comment on the question above?

**Comment by ericheatspersimmons** [comment] 2023-11-07 02:20
I had the same high level question as we're actually running into this being a problem (dp is not always a nice power of 2).

But I don't understand the second line of questions, as the linked lines by @jiayulu seem to both point to the numel ?

**Comment by nrailg** [comment] 2023-11-07 03:07
+1.

**Comment by LiuXTao** [comment] 2023-11-07 03:09
In my scenario, dp_size cannot be a power of 2, which leads to my problem when i use distributed optimizer:

assert gbuf_size % data_parallel_world_size == 0, \
AssertionError: Each bucket's buffer size should be divisible by 112

**Comment by ericheatspersimmons** [comment] 2023-11-07 04:00
@jiayulu 

I think the resolution to this paradox is that .numel() is the size of the underlying data tensor, which is allocated in MemoryBuffer with the numel_padded and is not the same as the raw .numel field of the MemoryBuffer.

.numel() != .numel

Some better naming could have gone a long way here.

**Comment by deepakn94** [comment] 2023-11-07 04:09
Yup, that's right. I have a PR open internally right now to fix the root cause (i.e., in the PR, I pad each bucket individually to make sure this assertion never fires); I am also removing other field names that are confusing.

**Comment by ericheatspersimmons** [comment] 2023-11-07 04:19
Thanks Deepak!  For this and all the great work on the distributed optimizer generally.

**Comment by jiayulu** [comment] 2023-11-07 06:56
> @jiayulu
> 
> I think the resolution to this paradox is that .numel() is the size of the underlying data tensor, which is allocated in MemoryBuffer with the numel_padded and is not the same as the raw .numel field of the MemoryBuffer.
> 
> .numel() != .numel
> 
> Some better naming could have gone a long way here.

@ericheatspersimmons yes, that's what I mean. when `.numel` != `.numel()`, the distributed optimizer would produce wrong results. In the commit I linked above there's no assertion.

**Comment by deepakn94** [comment] 2023-11-07 06:59
Won't this assertion fail though? https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/optimizer/distrib_optimizer.py#L146

**Comment by jiayulu** [comment] 2023-11-07 07:02
> Won't this assertion fail though? https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/optimizer/distrib_optimizer.py#L146

`gbuf_size` is padded to be a multiple of `data_parallel_world_size`

https://github.com/NVIDIA/Megatron-LM/blob/115b6776813eb182237da6c8b9c78c6ae05d8ab1/megatron/model/distributed.py#L136-L137

**Comment by deepakn94** [comment] 2023-11-07 07:05
No, that's the full buffer. Each bucket is not padded:

```python
        bucket = model.grad_buffers[dtype].buckets[bucket_index]
        bucket_buffer = bucket.data
        gbuf_size = bucket_buffer.numel()
```

**Comment by jiayulu** [comment] 2023-11-07 07:09
I am talking about the commit i linked above: 115b6776813e, not the tip of main. there's no buckets in that commit

**Comment by deepakn94** [comment] 2023-11-07 07:14
Oh I see. I don't think it's incorrect. `max_gbuf_range_size = int(math.ceil(gbuf_size / data_parallel_world_size))` should give you the same thing as `numel_padded / data_parallel_world_size`.

**Comment by jiayulu** [comment] 2023-11-07 07:30
indeed, you are right. i totally missed that.

**Comment by LiuXTao** [comment] 2023-11-07 07:39
> Yup, that's right. I have a PR open internally right now to fix the root cause (i.e., in the PR, I pad each bucket individually to make sure this assertion never fires); I am also removing other field names that are confusing.

Can you send your PR link? I would like to refer to it. Thanks.

**Comment by deepakn94** [comment] 2023-11-07 17:29
This is on our internal Gitlab, I'll link to the merge commit here once it gets merged and pushed to this public-facing repository.

**Comment by deepakn94** [comment] 2023-11-09 22:32
Per-bucket padding code pushed here: https://github.com/NVIDIA/Megatron-LM/commit/443ce9f3f98fdc5a53c6b480c6e21b79944d198e. Please let me know if you run into any issues.

**Closed** 2023-11-26 06:41 UTC
