### ISSUE TITLE
Bug in data preprocessing

### ISSUE THREAD

**Issue by mayank31398** [NVIDIA/Megatron-LM#431] opened 2023-07-25 07:05 UTC
eos token is not included in the length as with the earlier data prerocessing script.
https://github.com/NVIDIA/Megatron-LM/blob/65da5be50cdaad2205e0bc96295bcaaf2c2c2a34/tools/preprocess_data.py#L91-L97
The eos token is added after length calculation and earlier script didn't calculate lenght and used `add_item` method.
We are now using `add_doc` which takes lengths and lengths are being calculated incorrectly since eos is added later.

@jon-barker

**Comment by mayank31398** [comment] 2023-07-31 18:36
@jon-barker @jaredcasper can you take a look at this?

**Comment by mayank31398** [comment] 2023-08-04 20:22
<img width="1191" alt="Screenshot 2023-08-05 at 1 51 49 AM" src="https://github.com/NVIDIA/Megatron-LM/assets/32954280/ec73b8fa-0551-4a38-a135-cfd02becd33c">
@jaredcasper @jon-barker 
seems like a bug that needs to be fixed urgently
left side is the old script for preprocess data and right is the new one.

As mentioned earlier, an eos token is missing.

**Comment by jon-barker** [comment] 2023-08-04 22:13
@mayank31398 What is the commit of your old script?

**Comment by jon-barker** [comment] 2023-08-04 22:33
It doesn't look to me like the issue is coming from the snippet of code you shared above. That's adding an EOD token to doc_ids, not an EOS token to the sentence and the length is based on the sentence. In the old script example where were you getting the sentence lengths from?

**Comment by mayank31398** [comment] 2023-08-05 02:47
@jon-barker I modified the following 3 methods in `MMapIndexedDatasetBuilder` class to add print statements.
```python
    def add_item(self, tensor):
        """
        add a sentence to the dataset, this might be an entire
        document depending on how we are splitting
        """
        # np_array is a sentence
        np_array = np.array(tensor.numpy(), dtype=self._dtype)
        self._data_file.write(np_array.tobytes(order='C'))
        # length of the sentence
        self._sizes.append(np_array.size)
        print("sizes", self._sizes)

    def add_doc(self, tensor, sizes):
        np_array = np.array(tensor, dtype=self._dtype)
        self._data_file.write(np_array.tobytes(order='C'))
        self._sizes.extend(sizes)
        self._doc_idx.append(len(self._sizes))
        print("sizes", self._sizes)
        print("doc_idx", self._doc_idx)

    def end_document(self):
        """
        ends the current document and adds the starting position of the next document
        """
        self._doc_idx.append(len(self._sizes))
        print("doc_idx", self._doc_idx)
```

For the older script, I am using the code before preprocess_data.py was replaced with preprocess_data_partitions.py. this is the hash: 7fc9611165da9111c325baf619cdbfad4ba4d5d9

**Comment by mayank31398** [comment] 2023-08-05 02:48
For me, I am not splitting docs into sentences. I have not passed `--split-sentences`

**Comment by mayank31398** [comment] 2023-08-05 05:26
<img width="1631" alt="Screenshot 2023-08-05 at 10 54 05 AM" src="https://github.com/NVIDIA/Megatron-LM/assets/32954280/d7f31cd1-64aa-438d-b383-da7db154ce8d">
This is what I get if I detokenize mid-way during training.
The left side is the correct sample as in the dataset. The right side is getting parts of wrong tokens from some other document.

This is tested with USPTO data.

**Comment by mayank31398** [comment] 2023-08-05 05:42
@jon-barker opened a PR which fixes this issue: https://github.com/NVIDIA/Megatron-LM/pull/447
I have tested this and it works.

**Comment by jon-barker** [comment] 2023-08-05 16:10
Thanks @mayank31398 - I'll get it merged in. I misunderstood the issue yesterday, I see now that the length is the length of the whole document and not an individual sentence so it should include the EOD token.

**Comment by jon-barker** [comment] 2023-08-05 18:19
Fix merged: https://github.com/NVIDIA/Megatron-LM/commit/0609f27fe8376f17ab65c001d3d8f35cd8175950, thanks

**Closed by jon-barker** 2023-08-05 18:19 UTC
Labels: bug

**Comment by mayank31398** [comment] 2023-08-05 20:23
Thanks a lot for the quick response :)
